cabal-version:   3.0
name:            valiant-example
version:         0.1.0.0
synopsis:        Example REST API using valiant
license:         BSD-3-Clause
license-file:    ../LICENSE
build-type:      Simple

executable valiant-example
  hs-source-dirs:   src
  main-is:          Main.hs
  default-language: GHC2021
  default-extensions:
    DeriveAnyClass
    DerivingStrategies
    LambdaCase
    OverloadedStrings

  other-modules:
    Queries

  build-depends:
    , aeson          >=2.1  && <2.3
    , base           >=4.17 && <5
    , bytestring
    , valiant
    , valiant-plugin
    , http-types     >=0.12 && <0.13
    , scotty         >=0.21 && <0.31
    , text
    , time

  ghc-options:
    -threaded -rtsopts -Wall -Werror
    -fplugin=Valiant.Plugin
    -fplugin-opt=Valiant.Plugin:sql-dir=sql
    -fplugin-opt=Valiant.Plugin:cache-dir=.valiant
