-- | Query definitions for the example app.
--
-- In a real project, these would be generated by @hsqlx generate@ or
-- written by hand with @queryFile@ and validated by the GHC plugin.
-- Here we use 'mkStatement' directly since the example doesn't require
-- the plugin to compile.
module Queries where

import Data.Int (Int32)
import Data.Text (Text)
import Data.Time (UTCTime)
import Hsqlx

-- Users ---------------------------------------------------------------------

-- | sql/users/find_by_id.sql
findUserById :: Statement Int32 (Int32, Text, Maybe Text, UTCTime)
findUserById = mkStatement
  "SELECT id, name, email, created_at FROM users WHERE id = $1"
  [23] -- int4
  ["id", "name", "email", "created_at"]
  "sql/users/find_by_id.sql"

-- | sql/users/list_all.sql
listUsers :: Statement () (Int32, Text, Maybe Text)
listUsers = mkStatement
  "SELECT id, name, email FROM users ORDER BY id"
  []
  ["id", "name", "email"]
  "sql/users/list_all.sql"

-- | sql/users/insert.sql (RETURNING id)
insertUser :: Statement (Text, Maybe Text) Int32
insertUser = mkStatement
  "INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id"
  [25, 25] -- text, text
  ["id"]
  "sql/users/insert.sql"

-- | Insert user without RETURNING (for batch inserts via 'executeBatch').
insertUserBatch :: Statement (Text, Maybe Text) ()
insertUserBatch = mkStatement
  "INSERT INTO users (name, email) VALUES ($1, $2)"
  [25, 25]
  []
  "sql/users/insert.sql"

-- | sql/users/delete.sql
deleteUser :: Statement Int32 ()
deleteUser = mkStatement
  "DELETE FROM users WHERE id = $1"
  [23] -- int4
  []
  "sql/users/delete.sql"

-- Posts ---------------------------------------------------------------------

-- | sql/posts/find_by_id.sql
findPostById :: Statement Int32 (Int32, Text, Maybe Text, Maybe UTCTime, Text)
findPostById = mkStatement
  "SELECT p.id, p.title, p.body, p.published_at, u.name as author_name \
  \FROM posts p JOIN users u ON u.id = p.author_id WHERE p.id = $1"
  [23] -- int4
  ["id", "title", "body", "published_at", "author_name"]
  "sql/posts/find_by_id.sql"

-- | sql/posts/list_recent.sql
listRecentPosts :: Statement Int32 (Int32, Text, Text, Maybe UTCTime)
listRecentPosts = mkStatement
  "SELECT p.id, p.title, u.name as author_name, p.published_at \
  \FROM posts p JOIN users u ON u.id = p.author_id \
  \WHERE p.published_at IS NOT NULL \
  \ORDER BY p.published_at DESC LIMIT $1"
  [23] -- int4
  ["id", "title", "author_name", "published_at"]
  "sql/posts/list_recent.sql"

-- | sql/posts/insert.sql (RETURNING id)
insertPost :: Statement (Int32, Text, Maybe Text) Int32
insertPost = mkStatement
  "INSERT INTO posts (author_id, title, body) VALUES ($1, $2, $3) RETURNING id"
  [23, 25, 25] -- int4, text, text
  ["id"]
  "sql/posts/insert.sql"

-- | sql/posts/publish.sql
publishPost :: Statement Int32 ()
publishPost = mkStatement
  "UPDATE posts SET published_at = now() WHERE id = $1 AND published_at IS NULL"
  [23] -- int4
  []
  "sql/posts/publish.sql"
